apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: dev
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx1g
          ports:
            - containerPort: 9200
            - containerPort: 9300
          # Добавьте секцию "podIP" с желаемым IP-адресом
      restartPolicy: Always

  selector:
    matchLabels:
      app: elasticsearch
