apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: hello-world-service
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx1g
        ports:
        - containerPort: 9200
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: hello-world-service
  labels:
    app: elasticsearch
spec:
  ports:
  - name: port-1
    port: 9200
  selector:
    app: elasticsearch

