apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.15.0
          ports:
            - containerPort: 5601
          env:
            - name: elasticsearch.url
              value: "http://10.244.1.3:9200"
          securityContext:
            privileged: true 
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: dev
spec:
  type: NodePort  # Change the type to NodePort
  selector:
    app: kibana
  ports:
    - name: tcp
      protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30001  # Set the desired NodePort value here
