apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: dev
data:
  logstash.conf: |
    input {
      file {
        path => "/logs/log.log"
        type => "logback"
      }
    }
    output {
      elasticsearch {
        hosts => ["10.244.1.8:9200"]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:6.5.4
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: dev
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - name: tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
