apiVersion: v1
kind: Service
metadata:
  name: exam-web
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: exam-web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-web
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exam-web
    spec:
      containers:
        - name: application
          image: yuhi1314/phpk8s:30
          imagePullPolicy: Always
          resources:
             requests:
                cpu: "0.1"
                memory: "100Mi"
          volumeMounts:
            -
              mountPath: /logs
              name: access-logs
          ports:
            - containerPort: 8080
        - name: fluentd-agent
          image: yuhi1314/fluentd-agent:30
          imagePullPolicy: Always
          volumeMounts:
            -
              mountPath: /tomcat/logs
              name: access-logs
      volumes:
        -
          name: access-logs
          emptyDir: {}
